#pragma once

enum ExitCode {
    EXITCODE_CHESS_ENGINE_ALLOCATION_FAILED = 100,
    EXITCODE_BOARD_ALLOCATION_FAILED,
    EXITCODE_VECTOR_ALLOCATION_FAILED,
    EXITCODE_VECTOR_REALLOCATION_FAILED,

    EXITCODE_EMPTY_PIECE_MODIFIED = 200,
    EXITCODE_PIECE_WITHOUT_VALID_TYPE,
    EXITCODE_PIECE_WITHOUT_VALID_COLOR,

    EXITCODE_VECTOR_OUT_OF_BOUNDS = 300,

    EXITCODE_UNREACHABLE = 900,
};

void __attribute__((noreturn)) crash(enum ExitCode exitcode);
